import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Comparely",
  description: "Generated by create next app",
};

const Footer: React.FC = () => {
  return (
    <footer className="bg-gray-800 text-white py-4">
      <div className="container mx-auto text-center text-sm">
        <div className="flex h-5 mx-4 items-center space-x-6 text-sm">
          <div>Blog</div>
          <Separator orientation="vertical" />
          <div>About Us</div>
          <Separator orientation="vertical" />
          <div>Contact Us</div>
        </div>
        <Separator className="my-4" />
        <h4 className="text-sm font-medium leading-none">
          &copy; {new Date().getFullYear()} Comparely. All rights reserved.
        </h4>
      </div>
    </footer>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
